name: Test and Build

on: [push]

jobs:
  test-spec:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run Unit Tests
        run: |
          npm ci
          npm run test-firefox-ci
        env:
          CI: true

  test-e2e:
    name: e2e Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run e2e Tests
        run: |
          npm ci
          ./node_modules/protractor/bin/webdriver-manager update
          npm run e2e-firefox-ci
        env:
          CI: true

  build:
    name: Build
    needs: [test-spec, test-e2e]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run Build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: ./dist
